// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_cloud_screen_screen_init(void)
{
    ui_cloud_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_cloud_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cloud_screen, lv_color_hex(0x6CD8E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cloud_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_search_ta1 = lv_textarea_create(ui_cloud_screen);
    lv_obj_set_width(ui_search_ta1, 700);
    lv_obj_set_height(ui_search_ta1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_search_ta1, 0);
    lv_obj_set_y(ui_search_ta1, 20);
    lv_obj_set_align(ui_search_ta1, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_search_ta1, "Goto...");
    lv_textarea_set_one_line(ui_search_ta1, true);
    lv_obj_add_state(ui_search_ta1, LV_STATE_USER_2);       /// States



    ui_files_panel1 = lv_obj_create(ui_cloud_screen);
    lv_obj_set_width(ui_files_panel1, 720);
    lv_obj_set_height(ui_files_panel1, 300);
    lv_obj_set_align(ui_files_panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_files_panel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_files_panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_control_panel1 = lv_obj_create(ui_cloud_screen);
    lv_obj_set_width(ui_control_panel1, 750);
    lv_obj_set_height(ui_control_panel1, 75);
    lv_obj_set_x(ui_control_panel1, 0);
    lv_obj_set_y(ui_control_panel1, -10);
    lv_obj_set_align(ui_control_panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_control_panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_control_panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_new_file1 = lv_imgbtn_create(ui_control_panel1);
    lv_imgbtn_set_src(ui_new_file1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_file_png, NULL);
    lv_obj_set_height(ui_new_file1, 40);
    lv_obj_set_width(ui_new_file1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_new_file1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_new_file1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_new_folder1 = lv_imgbtn_create(ui_control_panel1);
    lv_imgbtn_set_src(ui_new_folder1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_new_folder_png, NULL);
    lv_obj_set_height(ui_new_folder1, 40);
    lv_obj_set_width(ui_new_folder1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_new_folder1, LV_ALIGN_CENTER);

    ui_terminal1 = lv_imgbtn_create(ui_control_panel1);
    lv_imgbtn_set_src(ui_terminal1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_terminal_png, NULL);
    lv_obj_set_height(ui_terminal1, 40);
    lv_obj_set_width(ui_terminal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_terminal1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_terminal1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_file_control_panel1 = lv_obj_create(ui_cloud_screen);
    lv_obj_set_width(ui_file_control_panel1, 750);
    lv_obj_set_height(ui_file_control_panel1, 75);
    lv_obj_set_x(ui_file_control_panel1, 0);
    lv_obj_set_y(ui_file_control_panel1, -10);
    lv_obj_set_align(ui_file_control_panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_file_control_panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_file_control_panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_file_control_panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_panel_back1 = lv_imgbtn_create(ui_file_control_panel1);
    lv_imgbtn_set_src(ui_panel_back1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_undo_png, NULL);
    lv_obj_set_height(ui_panel_back1, 40);
    lv_obj_set_width(ui_panel_back1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_panel_back1, LV_ALIGN_CENTER);

    ui_delete_file1 = lv_imgbtn_create(ui_file_control_panel1);
    lv_imgbtn_set_src(ui_delete_file1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_delete_png, NULL);
    lv_obj_set_height(ui_delete_file1, 40);
    lv_obj_set_width(ui_delete_file1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_delete_file1, LV_ALIGN_CENTER);

    ui_cloud_download = lv_imgbtn_create(ui_file_control_panel1);
    lv_imgbtn_set_src(ui_cloud_download, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cloud_download_png, NULL);
    lv_obj_set_height(ui_cloud_download, 40);
    lv_obj_set_width(ui_cloud_download, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_cloud_download, LV_ALIGN_CENTER);

    ui_search_keyboard1 = lv_keyboard_create(ui_cloud_screen);
    lv_obj_set_width(ui_search_keyboard1, 750);
    lv_obj_set_height(ui_search_keyboard1, 200);
    lv_obj_set_x(ui_search_keyboard1, 0);
    lv_obj_set_y(ui_search_keyboard1, -20);
    lv_obj_set_align(ui_search_keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_search_keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_command_keyboard1 = lv_keyboard_create(ui_cloud_screen);
    lv_obj_set_width(ui_command_keyboard1, 750);
    lv_obj_set_height(ui_command_keyboard1, 200);
    lv_obj_set_x(ui_command_keyboard1, 0);
    lv_obj_set_y(ui_command_keyboard1, -20);
    lv_obj_set_align(ui_command_keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_command_keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_command_ta1 = lv_textarea_create(ui_cloud_screen);
    lv_obj_set_width(ui_command_ta1, 700);
    lv_obj_set_height(ui_command_ta1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_command_ta1, 0);
    lv_obj_set_y(ui_command_ta1, 20);
    lv_obj_set_align(ui_command_ta1, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_command_ta1, "Goto...");
    lv_textarea_set_one_line(ui_command_ta1, true);
    lv_obj_add_state(ui_command_ta1, LV_STATE_USER_2);       /// States
    lv_obj_add_flag(ui_command_ta1, LV_OBJ_FLAG_HIDDEN);     /// Flags



}
