// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main_screen
void ui_main_screen_screen_init(void);
lv_obj_t * ui_main_screen;
lv_obj_t * ui_imgs;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_search_ta;
lv_obj_t * ui_files_panel;
lv_obj_t * ui_control_panel;
lv_obj_t * ui_new_file;
lv_obj_t * ui_new_folder;
lv_obj_t * ui_terminal;
lv_obj_t * ui_file_control_panel;
lv_obj_t * ui_panel_back;
lv_obj_t * ui_delete_file;
lv_obj_t * ui_cloud_upload;
lv_obj_t * ui_search_keyboard;
lv_obj_t * ui_command_keyboard;
lv_obj_t * ui_command_ta;


// SCREEN: ui_cloud_screen
void ui_cloud_screen_screen_init(void);
lv_obj_t * ui_cloud_screen;
lv_obj_t * ui_search_ta1;
lv_obj_t * ui_files_panel1;
lv_obj_t * ui_control_panel1;
lv_obj_t * ui_new_file1;
lv_obj_t * ui_new_folder1;
lv_obj_t * ui_terminal1;
lv_obj_t * ui_file_control_panel1;
lv_obj_t * ui_panel_back1;
lv_obj_t * ui_delete_file1;
lv_obj_t * ui_cloud_download;
lv_obj_t * ui_search_keyboard1;
lv_obj_t * ui_command_keyboard1;
lv_obj_t * ui_command_ta1;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_keyboard_set_target(ui_search_keyboard,  ui_search_ta);
        _ui_keyboard_set_target(ui_command_keyboard,  ui_command_ta);
        _ui_keyboard_set_target(ui_search_keyboard1,  ui_search_ta1);
        _ui_keyboard_set_target(ui_command_keyboard1,  ui_command_ta1);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_screen_init();
    ui_cloud_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_main_screen);
}
