// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_main_screen
void ui_main_screen_screen_init(void);
extern lv_obj_t * ui_main_screen;
extern lv_obj_t * ui_imgs;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_search_ta;
extern lv_obj_t * ui_files_panel;
extern lv_obj_t * ui_control_panel;
extern lv_obj_t * ui_new_file;
extern lv_obj_t * ui_new_folder;
extern lv_obj_t * ui_terminal;
extern lv_obj_t * ui_file_control_panel;
extern lv_obj_t * ui_panel_back;
extern lv_obj_t * ui_delete_file;
extern lv_obj_t * ui_cloud_upload;
extern lv_obj_t * ui_search_keyboard;
extern lv_obj_t * ui_command_keyboard;
extern lv_obj_t * ui_command_ta;
// SCREEN: ui_cloud_screen
void ui_cloud_screen_screen_init(void);
extern lv_obj_t * ui_cloud_screen;
extern lv_obj_t * ui_search_ta1;
extern lv_obj_t * ui_files_panel1;
extern lv_obj_t * ui_control_panel1;
extern lv_obj_t * ui_new_file1;
extern lv_obj_t * ui_new_folder1;
extern lv_obj_t * ui_terminal1;
extern lv_obj_t * ui_file_control_panel1;
extern lv_obj_t * ui_panel_back1;
extern lv_obj_t * ui_delete_file1;
extern lv_obj_t * ui_cloud_download;
extern lv_obj_t * ui_search_keyboard1;
extern lv_obj_t * ui_command_keyboard1;
extern lv_obj_t * ui_command_ta1;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_default_file_png);    // assets/default file.png
LV_IMG_DECLARE(ui_img_check_png);    // assets/check.png
LV_IMG_DECLARE(ui_img_folder_png);    // assets/folder.png
LV_IMG_DECLARE(ui_img_add_file_png);    // assets/add file.png
LV_IMG_DECLARE(ui_img_new_folder_png);    // assets/new folder.png
LV_IMG_DECLARE(ui_img_terminal_png);    // assets/terminal.png
LV_IMG_DECLARE(ui_img_undo_png);    // assets/undo.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/delete.png
LV_IMG_DECLARE(ui_img_cloud_upload_png);    // assets/cloud_upload.png
LV_IMG_DECLARE(ui_img_cloud_download_png);    // assets/cloud download.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
